### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by allardy** [botpress/messaging#16] opened 2021-07-15 15:13 UTC
There are a couple of things that I think should be addressed:

1. The list of channels is hardcoded in the BP repository (https://github.com/botpress/botpress/blob/sm-extmsg-7-fix-hitlnex/src/bp/core/config/config-loader.ts#L176). This list should be provided by the Messaging process.  Once the messaging process is registered (https://github.com/botpress/botpress/blob/sm-extmsg-7-fix-hitlnex/src/bp/orchestrator/web-worker.ts#L61), it could query messaging to get a list of available channels, then update the botpress configuration (adding new channels to the file).

2. Channel configuration schemas should be moved from the main repository (in `channel-*/assets/config.schema.json` and into this one. 
A. There should be an endpoint on messaging that can be called to obtain this schema (to use in code editor)
B. There should also be an endpoint where you can get the default configuration from that schema (to generate the default file)

3. Messaging displays a lot of verbose and useless logs for the user.
A. The list of channels can be shortened to a single line. Space is wasted to display them on separate lines
B. Endpoints are all listed but usage is not clear, and even disabled channels are displayed
C. Logs should fit nicely with logs of other processes

4. The process of enabling and adding channels is really not clear. You need to update the `botpress.config.json` file, then somehow go on the code editor to create a `channel-name.json` file, and copy the config from somewhere else.
A. When you enable a channel in `botpress.config.json`, there should be some process which would automatically query messaging, get the default config for that channel, and create a `channel-name.json` file

5. Maybe we could simplify the channel creation process. We could either merge all `channel-*.json` files into a single `channels.json` file, or in a `channels` property in the `bot.config.json` file. We could even add an "environment" variable to ease development. What do you think? This would make it really easy to develop the bot once and move the archive between dev and prod

`bot.config.json or channels.json`
```js
channels: {
  prod: {
    slack: {}
    telegram: {}
}

// or 
channels: [
  {
    name: 'slack',
    enabled: true,
    env: 'prod',
    authToken: ''
  },
  {
    name: 'slack',
    env: 'dev',
    enabled: false,
   }
]
``` 

6. Once a channel is enabled, messaging should make a basic test to let the user know if the channel is properly configured, and it should give meaningful information to the user on how to do that.
A. When channel is enabled, display a log indicating so
B. Perform a small test to see if the channel configuration is actually correct
C. Either add a log or an endpoint that a user can query to get the complete URL required to configure the webhook on different services (ex: the full event / interactive URL required by slack)

7. I think we should add a "legacy" route handler on messaging, and redirect all requests done to `channel-*` to the messaging process (except for channel-web). Since we removed channels from the main BP repository, all the logic (including legacy logic) should be in messaging. This will make it much easier to update channels and fix issues by having all the logic at the same place.
A. Proxy all routes `channel-*` to messaging process
B. Print a warning to the user indicating that the old route is deprecated (/mod/channel-slack/events) and display the correct route

**Comment by samuelmasse** [comment] 2021-07-16 17:02
Channel configurations are now loaded from your bot.config.json file. All requests done to the `/api/v1/messaging` endpoint on the main server are proxied to the messaging server. The correct route to configure webhooks is now `/api/v1/messaging/webhooks/botId/channel`. The external url given to the messaging server is now  `externalUrl/api/v1/messaging` instead of just the same external url as the main server. This allows the messaging server to act independtly when choosing webhooks routes while still configuring the correct route relative to the main server.

Here is what we decided to do for the points you mentionned: 
1. We decided to remove the concept of gloabally disabling channels so this is not needed.
2. We'll generate the schemas from the messaging client typings when it's done. So messaging doesn't need to provide a route to fetch those schema.
3. This is fixed. Logs are pre-pended with `[Messaging]`. We also display the full url of the webhooks for channels that were setup.
![Screenshot from 2021-07-16 12-08-33](https://user-images.githubusercontent.com/59894025/125980727-c770a39e-d845-4453-8223-00d2480a5b6f.png)

4. Enabling a channel now requires you to put the config in the messaging section of your `bot.config.json` file. Templates are not automatically generated so you must read the documentation to know what to put here.
![Screenshot from 2021-07-16 12-43-04](https://user-images.githubusercontent.com/59894025/125981199-a3cbafb2-8c2e-41d2-992b-817bc236bfc3.png)

5. As we mentioned environment variables will be implemented for the whole config file so it's out of scope for us to implement it.

6. We want to improve diagsnotics to help users setup their channels, but for now this is not an immediate need to be able to release.
A. We print the webhook so it's equivalent
B. This depends a lot per channel. We'll do this eventually but for now we weren't doing this before so it's not a regression.
C. This is done

7. The legacy route handler is now in the legacy.ts file right next to messaging-service.ts. Since there is proper way to configure webhooks now (using `/api/vi/messaging/webooks`), we'll tell the user to use those routes and keep the legacy route working from the main repo. 
A. Instead of doing that we proxy knows routes to the correct webhook in messaging (so messaing doesn't need to know that legacy routes we in /api/vi/bots/botId/mod/channel-* etc)
B. This is done. For example :
![Screenshot from 2021-07-16 12-24-12](https://user-images.githubusercontent.com/59894025/125980707-ea0b9795-4599-406d-8b8a-2ea611b047a4.png)

**Closed** 2021-07-17 00:00 UTC
